# Generated by Django 5.0.2 on 2024-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="description",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
    ]
